#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Bundle-Perl6
version:      0.06
version_from: Perl6.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
